// component extends testRazunaBase
component extends="TestRazunaBase"{
	
	// Customization 
	function testCustomization() {
		Super.doRazLogin();
		selenium.click("link=admin admin");
		selenium.click("link=Administration");
		selenium.setspeed("1000");
		selenium.click("//a[contains(text(),'Customization')]");
		selenium.click("name=apply_global");
		selenium.click("css=div.headers");
		selenium.type("id=logoid", #expandpath('.')# & "\assets\img\logo.jpg");
		selenium.click("id=logosaveid");
		selenium.click("link=Refresh");
		selenium.type("id=loginid", #expandpath('.')# & "\assets\img\Desert.jpg");
		selenium.click("id=loginsaveid");
		selenium.click("xpath=(//a[contains(text(),'Refresh')])[2]");
		selenium.type("id=faviconid", #expandpath('.')# & "\assets\img\favicon.ico");
		selenium.click("id=faviconsaveid");
		selenium.click("xpath=(//a[contains(text(),'Refresh')])[3]");
		selenium.click("css=div.headers");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("css=div.headers");
		selenium.click("link=Remove");
		selenium.click("xpath=(//a[contains(text(),'Remove')])[2]");
		selenium.click("xpath=(//a[contains(text(),'Remove')])[3]");
		selenium.click("css=div.headers");
		selenium.click("//input[@value='Save Changes']");
		// User Options
		selenium.setspeed("3000");
		selenium.click("//div[@id='customization']/a[2]/div");
		selenium.click("name=folder_redirect_off");
		selenium.click("document.form_admin_custom.myfolder_create[1]");
		selenium.click("document.form_admin_custom.myfolder_upload[1]");
		selenium.click("document.form_admin_custom.request_access[1]");
		selenium.click("//div[@id='customization']/a[2]/div");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("//div[@id='customization']/a[2]/div");
		selenium.click("name=folder_redirect_off");
		selenium.click("name=myfolder_create");
		selenium.click("name=myfolder_upload");
		selenium.click("name=request_access");
		selenium.click("//div[@id='customization']/a[2]/div");
		selenium.click("//input[@value='Save Changes']");
		// Design
		selenium.click("//div[@id='customization']/a[3]/div");
		selenium.click("document.form_admin_custom.show_top_part[1]");
		selenium.click("document.form_admin_custom.show_bottom_part[1]");
		selenium.click("document.form_admin_custom.tab_collections[1]");
		selenium.click("document.form_admin_custom.tab_labels[1]");
		selenium.click("//div[@id='customization']/a[3]/div");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("//div[@id='customization']/a[3]/div");
		selenium.click("name=show_top_part");
		selenium.click("name=show_bottom_part");
		selenium.click("name=tab_collections");
		selenium.click("name=tab_labels");
		selenium.click("//div[@id='customization']/a[3]/div");
		selenium.click("//input[@value='Save Changes']");
		// Upload
		selenium.click("//div[@id='customization']/a[4]/div");
		selenium.click("document.form_admin_custom.tab_add_from_server[1]");
		selenium.click("document.form_admin_custom.tab_add_from_email[1]");
		selenium.click("document.form_admin_custom.tab_add_from_ftp[1]");
		selenium.click("document.form_admin_custom.tab_add_from_link[1]");
		selenium.click("//div[@id='customization']/a[4]/div");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("//div[@id='customization']/a[4]/div");
		selenium.click("name=tab_add_from_server");
		selenium.click("name=tab_add_from_email");
		selenium.click("name=tab_add_from_ftp");
		selenium.click("name=tab_add_from_link");
		selenium.click("//div[@id='customization']/a[4]/div");
		selenium.click("//input[@value='Save Changes']");
		// Shared Folder/Collection Options
		selenium.click("//div[@id='customization']/a[5]/div");
		selenium.click("name=share_folder");
		selenium.click("document.form_admin_custom.share_download_thumb[1]");
		selenium.click("name=share_download_original");
		selenium.click("name=share_comments");
		selenium.click("name=share_uploading");
		selenium.click("//div[@id='customization']/a[5]/div");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("//div[@id='customization']/a[5]/div");
		selenium.click("document.form_admin_custom.share_folder[1]");
		selenium.click("name=share_download_thumb");
		selenium.click("document.form_admin_custom.share_download_original[1]");
		selenium.click("document.form_admin_custom.share_comments[1]");
		selenium.click("document.form_admin_custom.share_uploading[1]");
		selenium.click("//div[@id='customization']/a[5]/div");
		selenium.click("//input[@value='Save Changes']");
		// Folderview
		selenium.click("//div[@id='customization']/a[6]/div");
		selenium.click("document.form_admin_custom.tab_images[1]");
		selenium.click("document.form_admin_custom.tab_videos[1]");
		selenium.click("document.form_admin_custom.tab_audios[1]");
		selenium.click("document.form_admin_custom.tab_other[1]");
		selenium.click("document.form_admin_custom.tab_pdf[1]");
		selenium.click("document.form_admin_custom.tab_doc[1]");
		selenium.click("document.form_admin_custom.tab_xls[1]");
		selenium.click("document.form_admin_custom.icon_select[1]");
		selenium.click("document.form_admin_custom.icon_refresh[1]");
		selenium.click("document.form_admin_custom.icon_show_subfolder[1]");
		selenium.click("document.form_admin_custom.icon_create_subfolder[1]");
		selenium.click("document.form_admin_custom.icon_favorite_folder[1]");
		selenium.click("document.form_admin_custom.icon_search[1]");
		selenium.click("document.form_admin_custom.icon_print[1]");
		selenium.click("document.form_admin_custom.icon_rss[1]");
		selenium.click("document.form_admin_custom.icon_word[1]");
		selenium.click("document.form_admin_custom.icon_metadata_import[1]");
		selenium.click("document.form_admin_custom.icon_metadata_export[1]");
		selenium.click("document.form_admin_custom.icon_download_folder[1]");
		selenium.click("//div[@id='customization']/a[6]/div");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("//div[@id='customization']/a[6]/div");
		selenium.click("name=tab_images");
		selenium.click("name=tab_videos");
		selenium.click("name=tab_audios");
		selenium.click("name=tab_other");
		selenium.click("name=tab_pdf");
		selenium.click("name=tab_doc");
		selenium.click("name=tab_xls");
		selenium.click("name=icon_select");
		selenium.click("name=icon_refresh");
		selenium.click("name=icon_show_subfolder");
		selenium.click("name=icon_create_subfolder");
		selenium.click("name=icon_favorite_folder");
		selenium.click("name=icon_search");
		selenium.click("name=icon_print");
		selenium.click("name=icon_rss");
		selenium.click("name=icon_word");
		selenium.click("name=icon_metadata_import");
		selenium.click("name=icon_metadata_export");
		selenium.click("name=icon_download_folder");
		selenium.click("//div[@id='customization']/a[6]/div");
		selenium.click("//input[@value='Save Changes']");
		// File Detail
		selenium.click("//div[@id='customization']/a[7]/div");
		selenium.click("document.form_admin_custom.tab_metadata[1]");
		selenium.click("document.form_admin_custom.tab_convert_files[1]");
		selenium.click("document.form_admin_custom.tab_comments[1]");
		selenium.click("document.form_admin_custom.tab_versions[1]");
		selenium.click("document.form_admin_custom.tab_sharing_options[1]");
		selenium.click("document.form_admin_custom.tab_history[1]");
		selenium.click("document.form_admin_custom.button_send_email[1]");
		selenium.click("document.form_admin_custom.button_send_ftp[1]");
		selenium.click("document.form_admin_custom.button_basket[1]");
		selenium.click("document.form_admin_custom.button_add_to_collection[1]");
		selenium.click("document.form_admin_custom.button_print[1]");
		selenium.click("document.form_admin_custom.req_filename[1]");
		selenium.click("name=req_description");
		selenium.click("name=req_keywords");
		selenium.click("xpath=(//input[@value='Save Changes'])[2]");
		selenium.click("//div[@id='customization']/a[7]/div");
		selenium.click("//input[@value='Save Changes']");
		selenium.click("//div[@id='customization']/a[7]/div");
		selenium.click("name=tab_metadata");
		selenium.click("name=tab_convert_files");
		selenium.click("name=tab_comments");
		selenium.click("name=tab_versions");
		selenium.click("name=tab_sharing_options");
		selenium.click("name=tab_history");
		selenium.click("name=button_send_email");
		selenium.click("name=button_send_ftp");
		selenium.click("name=button_basket");
		selenium.click("name=button_add_to_collection");
		selenium.click("name=button_print");
		selenium.click("name=req_filename");
		selenium.click("document.form_admin_custom.req_description[1]");
		selenium.click("document.form_admin_custom.req_keywords[1]");
		selenium.click("//div[@id='customization']/a[7]/div");
		selenium.click("xpath=(//input[@value='Save Changes'])[2]");
		Super.doRazLogout();
	}
}